image: node:10
stages:
  - test
before_script:
  - yarn install --pure-lockfile --prefer-offline --cache-folder .yarn
test:
  stage: test
  script:
    - yarn lint
    - yarn test
    - yarn build
cache:
  paths:
    - node_modules/
    - .yarn